# Generated by Django 3.2.7 on 2021-09-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20210928_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagebox',
            name='date',
        ),
    ]
