# Generated by Django 3.2.7 on 2021-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_messagebox_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebox',
            name='room_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
